---
- name: Parse CSV to JSON
  hosts: localhost
  gather_facts: no

  tasks:
    - name: parse csv and make vars file
      command: "python csv_to_yaml.py TP.csv"

- name: Generate Configuration
  hosts: localhost
  gather_facts: False
  vars:
    - debug: False
  vars_files:
    - TP.yaml
  
  tasks:
    - name: Print vars_file
      debug: var=csv_data
      when: debug

    - name: Generate configuration
      template:
        src: "./conf_template.j2"
        dest: "./{{item.name}}.txt"
      with_items: "{{csv_data}}"